  [mcp_servers.rider]
    url = "http://127.0.0.1:64482/stream"

[mcp_servers.rider.tools.get_file_problems]
approval_mode = "approve"

[mcp_servers.rider.tools.findTests]
approval_mode = "approve"

[mcp_servers.rider.tools.execute_run_configuration]
approval_mode = "approve"

[mcp_servers.rider.tools.lint_files]
approval_mode = "approve"

[mcp_servers.rider.tools.apply_patch]
approval_mode = "approve"

[mcp_servers.rider.tools.build_solution_start]
approval_mode = "approve"

[mcp_servers.rider.tools.build_solution_state]
approval_mode = "approve"

[mcp_servers.rider.tools.get_solution_projects]
approval_mode = "approve"

[mcp_servers.rider.tools.execute_terminal_command]
approval_mode = "approve"

[mcp_servers.rider.tools.get_project_problems]
approval_mode = "approve"

[sandbox_workspace_write]
network_access = true

[features.network_proxy]
enabled = true
domains = { "**.nuget.org" = "allow" }
